# Generated by Django 4.1 on 2022-08-21 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_review_scope_alter_review_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='confirmation_code',
            new_name='conformation_code',
        ),
    ]
