# Generated by Django 4.1 on 2022-08-21 18:13

import api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_confirmation_code_newuser_conformation_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='conformation_code',
        ),
        migrations.AlterField(
            model_name='title',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.SmallIntegerField(null=True, validators=[api.utils.date_not_in_future]),
        ),
    ]
