# Generated by Django 4.1 on 2022-09-14 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_title_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='scope',
            new_name='score',
        ),
    ]
